---
title: "Exhaustive Permutation Test"
author: "Karl Broman, Christina Koch"
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: yes
---

```{r chunk_opts, include=FALSE}
library(knitr)
knitr::opts_chunk$set(results="hide", echo=FALSE)
```

This report performs an exhaustive permutation test
(with the t-statistic) on two vectors and plots the results

```{r utility}
#     returns binary representation of 1:(2^n)
binary.v <-
    function(n)
{
    x <- 1:(2^n)
    mx <- max(x)
    digits <- floor(log2(mx))
    ans <- 0:(digits-1); lx <- length(x)
    x <- matrix(rep(x,rep(digits, lx)),ncol=lx)
    (x %/% 2^ans) %% 2
}
```

```{r perm_fcn}
# exhaustive permutation test with the t-statistic
perm.test <-
    function(x, y, var.equal=TRUE)
{
    # number of data points
    kx <- length(x)
    ky <- length(y)
    n <- kx + ky

    # Data re-compiled
    X <- c(x,y)
    z <- rep(1:0,c(kx,ky))

    tobs <- t.test(x,y,var.equal=var.equal)$statistic

    o <- binary.v(n)  # indicator of all possible samples
    o <- o[,apply(o,2,sum)==kx]
    nc <- choose(n,kx)
    allt <- 1:nc
    for(i in 1:nc) {
        xn <- X[o[,i]==1]
        yn <- X[o[,i]==0]
        allt[i] <- t.test(xn,yn,var.equal=var.equal)$statistic
    }

    attr(allt, "tobs") <- tobs

    allt
}
```

We will run the permutation test on these vectors: 

```{r input, results="show"}
(x <- c(6.20, 5.72, 6.07, 6.75, 5.50, 6.39, 4.30, 4.96, 5.48))
(y <- c(6.49, 6.52, 6.28, 8.59, 7.18, 4.92, 6.74, 7.27))
```

```{r perm_test}
permt <- perm.test(x, y)
```

```{r t_stat}
# grab the observed t-statistic (saved as attribute)
tobs <- attr(permt, "tobs")
```

```{r p_val}
# calculate p-value
pval <- mean(abs(permt) >= abs(tobs))
```

After running the permutation test, the t-statistic is `r tobs` and the p-value is `r pval`.  The graph corresponding to these values looks like this: 

```{r plot, results="show"}
hist(permt, breaks=200, xlab="t-statistic", las=1,
     main = paste("P-value =", round(pval, 3)))
abline(v=tobs, lwd=2, col="violetred")
dev.off()
```

####Tools used in this report
```{r session_info, results="show"}
library(devtools)
devtools::session_info()
```
